import { useConnectionStore } from '@/store/connection'

function getBase(): string {
  return useConnectionStore.getState().apiUrl || ''
}

function getHeaders(): Record<string, string> {
  const { token } = useConnectionStore.getState()
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }
  if (token) headers['Authorization'] = `Bearer ${token}`
  return headers
}

export async function fetchJSON<T>(path: string): Promise<T> {
  const res = await fetch(`${getBase()}${path}`, { headers: getHeaders() })
  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error(body.message ?? `${res.status} ${res.statusText}`)
  }
  return res.json()
}

// Types matching the claw API spec

export interface Driver {
  arch: string
  arch_version: string
  driver_version: string
  driver_type: string
  path: string
}

export interface Instance {
  id: string
  arch: string
  group: string
  folder: string
  jid: string
  state: string
  age: string
  is_main: boolean
}

export interface HealthCheck {
  name: string
  status: 'pass' | 'warn' | 'fail'
  detail: string
  remediation?: string
}

export interface Installation {
  arch: string
  source_dir: string
  checks: HealthCheck[]
  summary: { pass: number; warn: number; fail: number }
  overall: string
}

export interface Group {
  arch: string
  source_dir: string
  jid: string
  name: string
  folder: string
  trigger: string
  is_main: boolean
  requires_trigger: boolean
}

export interface Session {
  session_id: string
  group: string
  started_at: string
  last_active: string
  message_count: number
  summary: string
  resumable?: boolean
}

/**
 * A single agent run's token usage, returned by GET /api/v1/usage.
 * Token fields mirror the Anthropic API usage object. The estimated cost
 * is computed server-side using published Claude Sonnet 4 rates.
 */
export interface UsageRow {
  /** Architecture that ran this agent (e.g. "nanoclaw"). */
  arch: string
  /** Group folder name (e.g. "main", "dev"). */
  group_folder: string
  /** Chat JID that triggered the agent run. */
  chat_jid: string
  /** ISO 8601 timestamp when the run completed. */
  completed_at: string
  /** Wall-clock duration of the agent run in milliseconds. */
  duration_ms: number
  /** Non-cached input tokens consumed. */
  input_tokens: number
  /** Output tokens generated by the model. */
  output_tokens: number
  /** Input tokens served from the Anthropic prompt cache. */
  cache_read_input_tokens: number
  /** Input tokens written to the Anthropic prompt cache. */
  cache_creation_input_tokens: number
  /** Estimated cost in USD based on published rates. */
  estimated_cost_usd: number
}

/** Aggregate totals across all rows in a usage response. */
export interface UsageTotals {
  /** Total number of agent runs in the result set. */
  runs: number
  /** Sum of non-cached input tokens across all runs. */
  input_tokens: number
  /** Sum of output tokens across all runs. */
  output_tokens: number
  /** Sum of cache-read input tokens across all runs. */
  cache_read_input_tokens: number
  /** Sum of cache-creation input tokens across all runs. */
  cache_creation_input_tokens: number
  /** Sum of estimated costs across all runs. */
  estimated_cost_usd: number
}

/** Response shape for GET /api/v1/usage. */
export interface UsageResponse {
  /** Individual run records, ordered by completed_at DESC. */
  rows: UsageRow[]
  /** Aggregated totals across all returned rows. */
  totals: UsageTotals
}
